name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: build wasm
        working-directory: ./simulation
        run: cargo b
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: install deps frontend
        working-directory: ./frontend
        run: pnpm i
      - name: build frontend
        run: pnpm build
        working-directory: ./frontend
      - name: archive prod articfacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
